services:
  app:
    image: openmind:${APP_VERSION:-latest}
    container_name: openmind
    build:
      context: .
      args:
        APP_VERSION: ${APP_VERSION:-latest}
        NUXT_SITE_URL: ${NUXT_SITE_URL}
        NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}
        NUXT_PUBLIC_APP_VERSION: ${NUXT_PUBLIC_APP_VERSION}
    environment:
      NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL}
      NUXT_PUBLIC_APP_VERSION: ${NUXT_PUBLIC_APP_VERSION}
      NUXT_SITE_URL: ${NUXT_SITE_URL}
      NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openmind.rule=Host(`openmind.ismaelrakoto.com`)"
      - "traefik.http.routers.openmind.entrypoints=websecure"
      - "traefik.http.routers.openmind.tls.certresolver=leresolver"
    networks:
      - web

networks:
  web:
    external: true