services:
  app:
    build:
      context: .
      args:
        NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL}
        NUXT_PUBLIC_APP_VERSION: ${NUXT_PUBLIC_APP_VERSION:-latest}
        NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}

    environment:
      NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL}
      NUXT_PUBLIC_APP_VERSION: ${NUXT_PUBLIC_APP_VERSION:-latest}
      NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}
      DATABASE_URL: ${DATABASE_URL}
      NUXT_SESSION_PASSWORD: ${NUXT_SESSION_PASSWORD}
      NUXT_OG_IMAGE_SECRET: ${NUXT_OG_IMAGE_SECRET}
      NUXT_S3_HOST: ${NUXT_S3_HOST}
      NUXT_S3_REGION: ${NUXT_S3_REGION}
      NUXT_S3_ACCESS_KEY: ${NUXT_S3_ACCESS_KEY}
      NUXT_S3_SECRET_KEY: ${NUXT_S3_SECRET_KEY}
      NUXT_BREVO_API_KEY: ${NUXT_BREVO_API_KEY}

    restart: always
