services:
  app:
    build:
      context: .
      args:
        NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL}
        NUXT_PUBLIC_APP_VERSION: ${NUXT_PUBLIC_APP_VERSION:-latest}
        NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}
        NUXT_PUBLIC_SUPABASE_URL: ${NUXT_PUBLIC_SUPABASE_URL}
        NUXT_PUBLIC_SUPABASE_KEY: ${NUXT_PUBLIC_SUPABASE_KEY}

    environment:
      NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL}
      NUXT_PUBLIC_APP_VERSION: ${NUXT_PUBLIC_APP_VERSION:-latest}
      NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}
      NUXT_PUBLIC_SUPABASE_URL: ${NUXT_PUBLIC_SUPABASE_URL}
      NUXT_PUBLIC_SUPABASE_KEY: ${NUXT_PUBLIC_SUPABASE_KEY}
      NUXT_SUPABASE_SECRET_KEY: ${NUXT_SUPABASE_SECRET_KEY}

    restart: always
