export const articleConfig = {
  ID_LENGTH: 21,
  TITLE_MIN_LENGTH: 5,
  TITLE_MAX_LENGTH: 70,
  SUMMARY_MIN_LENGTH: 5,
  SUMMARY_MAX_LENGTH: 200,
  CONTENT_MIN_LENGTH: 5,
  CONTENT_MAX_LENGTH: 10000,
  IS_VISIBLE_DEFAULT_VALUE: true,
  SLUG_SUFFIX_LENGTH: 6,
};
