export const userConfig: {
  USERNAME_MIN_LENGTH: number;
  USERNAME_MAX_LENGTH: number;
  NAME_MIN_LENGTH: number;
  NAME_MAX_LENGTH: number;
  FIRST_NAME_MIN_LENGTH: number;
  FIRST_NAME_MAX_LENGTH: number;
  EMAIL_MAX_LENGTH: number;
  USER_ROLE_DEFAULT_VALUE: "user";
  TAGS_MIN_SIZE: number;
  TAGS_MAX_SIZE: number;
} = {
  USERNAME_MIN_LENGTH: 6,
  USERNAME_MAX_LENGTH: 50,
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 20,
  FIRST_NAME_MIN_LENGTH: 3,
  FIRST_NAME_MAX_LENGTH: 20,
  EMAIL_MAX_LENGTH: 50,
  USER_ROLE_DEFAULT_VALUE: "user",
  TAGS_MIN_SIZE: 3,
  TAGS_MAX_SIZE: 10,
};
