import type { ComposerTranslation } from 'vue-i18n';

// @link https://github.com/toss/es-toolkit/blob/main/src/object/mapValues.ts
/**
 * Creates a new object with the same keys as the given object, but with values generated
 * by running each own enumerable property of the object through the iteratee function.
 *
 * @template T - The type of the object.
 * @template K - The type of the keys in the object.
 * @template V - The type of the new values generated by the iteratee function.
 *
 * @param {T} object - The object to iterate over.
 * @param {(value: T[K], key: K, object: T) => V} getNewValue - The function invoked per own enumerable property.
 * @returns {Record<K, V>} - Returns the new mapped object.
 *
 * @example
 * // Example usage:
 * const obj = { a: 1, b: 2 };
 * const result = mapValues(obj, (value) => value * 2);
 * console.log(result); // { a: 2, b: 4 }
 */
export function mapValues<T extends object, K extends keyof T, V>(
  object: T,
  getNewValue: (value: T[K], key: K, object: T) => V
): Record<K, V> {
  const result = {} as Record<K, V>;
  const keys = Object.keys(object);

  for (let i = 0; i < keys.length; i++) {
    const key = keys[i] as K;
    const value = object[key];

    result[key] = getNewValue(value, key, object);
  }

  return result;
}

const translateOptionsIfNecessary = (
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  t: ComposerTranslation<Record<string, unknown>, any>,
  errorDataIssue: ResponseErrorIssue
): ResponseErrorIssue[1] => {
  if (errorDataIssue[0] === 'zodI18n.errors.invalid_type') {
    return mapValues(errorDataIssue[1], value => t(`zodI18n.types.${value}`));
  }

  if (
    errorDataIssue[0].startsWith('zodI18n.errors.invalid_string.') &&
    'validation' in errorDataIssue[1]
  ) {
    return mapValues(errorDataIssue[1], value =>
      t(`zodI18n.validations.${value}`)
    );
  }

  return errorDataIssue[1];
};

export const translateResponseErrorData = <TInput>(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  t: ComposerTranslation<Record<string, unknown>, any>,
  errorData: ResponseErrorData<TInput>
): Record<keyof ResponseErrorData<TInput>, string | string[] | undefined> => {
  return mapValues(errorData, errorDataIssue => {
    if (!errorDataIssue) {
      return undefined;
    }

    return t(errorDataIssue[0], translateOptionsIfNecessary(t, errorDataIssue));
  });
};
